# Generated by Django 3.0.7 on 2021-12-23 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
