# Generated by Django 3.0.7 on 2021-12-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211223_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.CharField(max_length=10, verbose_name='Data de Nascimento'),
        ),
    ]
