# Generated by Django 3.0.7 on 2021-12-22 17:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20211222_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id_consulta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('data', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente')),
            ],
        ),
    ]
