# Generated by Django 3.0.7 on 2021-12-21 16:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id_endereco', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=150)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente')),
            ],
        ),
    ]
